---
severity_overrides:
  # Set minimum severity level for reporting
  LOW: WARNING
  MEDIUM: ERROR
  HIGH: ERROR
  CRITICAL: ERROR

# Add specific checks to exclude if needed
# exclude:
#   - AWS001

exclude_paths:
  - .terraform/
  - test/
  - examples/

minimum_severity: LOW
