---
severity_overrides:
  # Set minimum severity level for reporting
  LOW: WARNING
  MEDIUM: ERROR
  HIGH: ERROR
  CRITICAL: ERROR

exclude:
  # Add specific checks to exclude if needed
  # - AWS001

exclude_paths:
  - .terraform/
  - test/
  - examples/

minimum_severity: LOW
